// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    partial class MySQLContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Context.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "Colar",
                            Description = "Colar da Sonserina",
                            ImageURL = "https://nerdstore.com.br/produto/colar-flamula-sonserina/",
                            Name = "Colar Flamula Sonserina",
                            Price = 41.9m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "Colar",
                            Description = "Colar da Lufa-Lufa",
                            ImageURL = "https://nerdstore.com.br/wp-content/uploads/2020/11/colar-flamula-lufa-lufa.jpg.webp",
                            Name = "Colar Flamula Lufa-Lufa",
                            Price = 41.9m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Colar",
                            Description = "Colar da Grifinoria",
                            ImageURL = "https://nerdstore.com.br/wp-content/uploads/2020/11/colar-flamula-grifinoria.jpg.webp",
                            Name = "Colar Flamula Grifinoria",
                            Price = 41.9m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Colar",
                            Description = "Colar da Corvinal",
                            ImageURL = "https://nerdstore.com.br/wp-content/uploads/2020/11/colar-flamula-corvinal.jpg.webp",
                            Name = "Colar Flamula Corvinal",
                            Price = 41.9m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Adesivo",
                            Description = "Adesivo Árvore de Gondor",
                            ImageURL = "https://nerdstore.com.br/wp-content/uploads/2023/07/vitrine-adesivo-arvore-de-gondor-02-nerdstore.jpg.webp",
                            Name = "Adesivo Árvore de Gondor",
                            Price = 9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
